# Generated by Django 4.1.2 on 2022-10-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.IntegerField()),
                ('data', models.TextField(max_length=80)),
                ('country', models.TextField(max_length=30)),
            ],
        ),
    ]
