# Generated by Django 4.1.2 on 2022-10-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packetmodel',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
